### PR TITLE
Improved node movement and resizing

### PR DESCRIPTION
**Pull request by stefan-s29**
- Added DragHandlers for edges to resize a node in only one dimension
- Added "resizeMode" attribute to Nodes to configure the amount of drag handlers
- Made movement and resizing of nodes smoother by replacing GestureDetector by Listener widget
- Implemented snapping to grid on resize
- Implemented snapping to grid on movement within the Node class without the need for a formatter, also snapping at the right or bottom edges (depending on proximity)
- Added "snapMovementToGrid" and "snapResizeToGrid" attributes to Controller to make snapping configurable individually for both actions
- Added "Settings" menu item with "Snap To Grid" option

### CODE REVIEW

**Comment by rodydavis** [comment]
This is amazing! Will test soon 🎉

**Comment by rodydavis** [comment]
Tested it and looks amazing!

Screenshot 2024-08-18 at 8 54 59 PM

**Comment by rodydavis** [comment]
Thank you so much for the PR!

**Comment by rodydavis** [comment]
Published 0.0.10! 🎉

**Comment by stefan-s29** [comment]
I am happy you like it! 😀 

Also thanks for your work on this great package! I might use it for a little side-project and needed these features, so I thought I might as well just add them to the package. 😄

The Readme should probably be updated at some point.

**Pull request merged**
